export const USER_BASE_INSTANCE = {
  first_name: "",
  last_name: "",
  name: "",
  title: "",
  about: "",
  emails: [],
  photo: null,
  banner: null,
  website: "string",
  phone: null,
  country: "BD",
  city: null,
  location: null,
  timezone: null,
  language: "en",
  urls: null,
  created_at: new Date(),
  updated_at: new Date(),
  instance_id: null,
};
